### ISSUE TITLE
Ruby 3+ compatibility

### ISSUE THREAD

**Issue by gael-ian** [max-power/postal_address#3]
Hello,

Since Ruby 3 (maybe 3.1?), aliases are not automatically resolved by `YAML.load_file` unless explicitely asked to with an additional `aliases: true` option.

This implies theses two methods should be updated to be compatible with Ruby 3+ YAML file loading:

````diff
module Postal
  class << self
    # […]
    def address_formats
-     @address_formats ||= YAML.load_file(path_for(:address_formats))
+     @address_formats ||= YAML.load_file(path_for(:address_formats), aliases: true)
    end
  
    def country_names
-     @country_names ||= YAML.load_file(path_for(:country_names))
+     @country_names ||= YAML.load_file(path_for(:country_names), aliases: true)
    end
  end
end
````

These are really minor changes but, without, your gem is stuck with Ruby 2.7.

If it can help to quickly get an updated release with Ruby 3+ support, I can forge a pull request to update this (and the CI configuration?)

**Comment by max-power** [comment]
Hi Gaël-Ian,Please prepare the pull request. I’ll merge it immediately. I haven’t done programming in a while, so thank you. Von meinem Hosentaschencomputer gesendetAm 05.05.2023 um 12:08 schrieb Gaël-Ian ***@***.***>:﻿
Hello,
Since Ruby 3 (maybe 3.1?), aliases are not automatically resolved by YAML.load_file unless explicitely asked to with an additional aliases: true option.
This implies theses two methods should be updated to be compatible with Ruby 3+ YAML file loading:
module Postal
  class << self
    # […]
    def address_formats
-     @address_formats ||= YAML.load_file(path_for(:address_formats))
+     @address_formats ||= YAML.load_file(path_for(:address_formats), aliases: true)
    end
  
    def country_names
-     @country_names ||= YAML.load_file(path_for(:country_names))
+     @country_names ||= YAML.load_file(path_for(:country_names), aliases: true)
    end
  end
end
These are really minor changes but, without, your gem is stuck with Ruby 2.7.
If it can help to quickly get an updated release with Ruby 3+ support, I can forge a pull request to update this (and the CI configuration?)

**Comment by max-power** [comment]
alright, I applied the changes. please report any problems.

**Comment by gael-ian** [comment]
Hi @max-power 

Thank you for applying the changes, I had no time last week-end to build a pull request. Tested locally, your fix works as expected.

Can you forge a new release and push it to Rubygems?

**Comment by max-power** [comment]
Hi,

i pushed the new version to rubygems. I hope everything works fine for you.

**Comment by gael-ian** [comment]
Thanks a lot! 👍
